### ISSUE TITLE
Weapon unique id consistency

### ISSUE THREAD

**Issue by quancore** [markus-wa/demoinfocs-golang#119] opened 2019-06-05 11:03 UTC
**Describe the bug**
Currently, I am trying to store all dropped and picked up weapon items for a given round. The problem is that unique ids of weapons that already dropped and picked up never matched. As far as I understand, weapon unique ids have been created with a weapon entity in item drop and item pickup events again and again.
**To Reproduce**
Any demo file.
**Expected behavior**
The parser should give the same unique id for the same weapon. For Example, if a player dropped a weapon and then other player picked up this weapon, itemdrop and itempickup events should serve with same weapon entity with the same unique id.

**Comment by markus-wa** [comment] 2019-06-05 11:08
AFAIK we don't have any correlation because the entity is destroyed and re-created. But I'll try to look into it once I can find some time.

**Comment by quancore** [comment] 2019-06-05 11:33
Thank you for your fast response. Just a friendly wish, If you find some time, please prioritize the issue of POV.

**Comment by markus-wa** [comment] 2019-06-05 11:37
Will do

**Comment by markus-wa** [comment] 2019-07-04 20:05
Sorry for the silence on this, I haven't had time to look into it and it seems to be quite tricky.

Will try to do it soon(TM)

**Comment by markus-wa** [comment] 2019-07-13 09:31
I can't reproduce this. Can you provide some code?

Demo: https://gitlab.com/markus-wa/cs-demos/blob/master/valve_matchmaking.dem

At tick 22894 a CT with an AWP is killed and at 23770 the weapon is picked up by the T.
Weapon IDs stay the same (last field in the output, 898194423829772516)
```
22894 drop &{232 AWP <nil> 6 7 0 models/weapons/v_snip_awp.mdl 1 898194423829772516}
...
23770 pick up &{232 AWP 0xc000524800 6 7 0 models/weapons/v_snip_awp.mdl 1 898194423829772516}
```

**Comment by xavier-rodet** [comment] 2019-07-18 15:54
I'm having the same issue, you can try with this demo : https://www.hltv.org/download/demo/50987
**Krimz is dropping an AK-47 to Brollan at round 4 (Mirage).**

Code  : 
```
package main

import (
	"fmt"
	"os"

	dem "github.com/markus-wa/demoinfocs-golang"
	events "github.com/markus-wa/demoinfocs-golang/events"
)


func main() {

    isGameLive := false
    roundNumber := 0

	f, err := os.Open("vitality-vs-fnatic-m1-mirage.dem")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	p := dem.NewParser(f)


	/***** ROUND HANDLING *****/
    // Match Started
    p.RegisterEventHandler(func(e events.MatchStart) {

        isGameLive = true
        roundNumber = 1
    })

    // Round Started
    p.RegisterEventHandler(func(e events.RoundStart) {

        if(isGameLive) {

            // Prepare new round
            roundNumber++

            fmt.Printf("Round %d has just started\n", roundNumber)
        }
    })
    /***** ROUND HANDLING *****/



    /***** TESTING AREA *****/
    p.RegisterEventHandler(func(e events.ItemDrop) {

        if(isGameLive) {

            fmt.Printf("Player %s Dropped weapon %s (%d)\n", e.Player.Name, e.Weapon.Weapon.String(), e.Weapon.UniqueID())
        }
    })

    p.RegisterEventHandler(func(e events.ItemPickup) {

        if(isGameLive) {

            fmt.Printf("Player %s Picked up weapon %s (%d)\n", e.Player.Name, e.Weapon.Weapon.String(), e.Weapon.UniqueID())
        }
    })
    /***** TESTING AREA *****/


	// Parse to end
	err = p.ParseToEnd()
	if err != nil {
		panic(err)
	}
}
```

Look for : 

> Round 4 has just started
> Player KRIMZ Dropped weapon AK-47 (7687186813104574367)
> Player Brollan Picked up weapon AK-47 (1151812229553087684)

**Comment by markus-wa** [comment] 2019-07-18 21:40
Ah I see now. This only happens with `ItemEquip`, `ItemRemove` & `ItemPickup` events, internally we have a consistent ID.

```
Player KRIMZ Dropped weapon AK-47 (7687186813104574367)
internal: 42621 drop &{465 AK-47 0xc000f59200 2 30 0 models/weapons/v_rif_ak47.mdl 0 6585732776071912872}
Player Brollan Picked up weapon AK-47 (1151812229553087684)
internal: 42633 pick up &{465 AK-47 0xc000f58400 2 30 0 models/weapons/v_rif_ak47.mdl 0 6585732776071912872}
```

Thanks for the repro!

**Comment by markus-wa** [comment] 2019-07-18 22:24
Can one of you please verify that #130 fixes the issue?
Thanks!

**Comment by xavier-rodet** [comment] 2019-07-19 08:51
You're reactive !

I didn't manage to try it because i don't know how to import a git branch for golang ?

I'm working with docker i tried to replace 
`RUN go get -u github.com/markus-wa/demoinfocs-golang`
by 
```
RUN git clone --single-branch --branch issue-119-ItemPickup-UniqueID https://github.com/markus-wa/demoinfocs-golang.git github.com/markus-wa/demoinfocs-golang
RUN cd github.com/markus-wa/demoinfocs-golang
# Automatically get all dependencies for this project
RUN go get -u ./...
```
 
But i got dependencies errors :

> Step 9/12 : RUN go get -u ./...
>  ---> Running in 182dfcbb564c
> github.com/dustin/go-heatmap/examples/wikipedia/wikipedia.go:14:2: cannot find package "github.com/dustin/go-humanize" in any of:
> 	/usr/local/go/src/github.com/dustin/go-humanize (from $GOROOT)
> 	/go/src/github.com/dustin/go-humanize (from $GOPATH)
> github.com/llgcode/draw2d/draw2dgl/gc.go:11:2: cannot find package "github.com/go-gl/gl/v2.1/gl" in any of:
> 	/usr/local/go/src/github.com/go-gl/gl/v2.1/gl (from $GOROOT)
> 	/go/src/github.com/go-gl/gl/v2.1/gl (from $GOPATH)
> github.com/llgcode/draw2d/draw2dpdf/fileutil.go:6:8: cannot find package "github.com/jung-kurt/gofpdf" in any of:
> 	/usr/local/go/src/github.com/jung-kurt/gofpdf (from $GOROOT)
> 	/go/src/github.com/jung-kurt/gofpdf (from $GOPATH)
> github.com/llgcode/draw2d/samples/helloworldgl/helloworldgl.go:10:2: cannot find package "github.com/go-gl/glfw/v3.1/glfw" in any of:
> 	/usr/local/go/src/github.com/go-gl/glfw/v3.1/glfw (from $GOROOT)
> 	/go/src/github.com/go-gl/glfw/v3.1/glfw (from $GOPATH)
> github.com/llgcode/draw2d/samples/postscript/postscript.go:9:2: cannot find package "github.com/llgcode/ps" in any of:
> 	/usr/local/go/src/github.com/llgcode/ps (from $GOROOT)
> 	/go/src/github.com/llgcode/ps (from $GOPATH)
> golang.org/x/image/font/sfnt/cmap.go:8:2: cannot find package "golang.org/x/text/encoding/charmap" in any of:
> 	/usr/local/go/src/golang.org/x/text/encoding/charmap (from $GOROOT)
> 	/go/src/golang.org/x/text/encoding/charmap (from $GOPATH)
> golang.org/x/tools/godoc/redirect/redirect.go:22:2: cannot find package "golang.org/x/net/context/ctxhttp" in any of:
> 	/usr/local/go/src/golang.org/x/net/context/ctxhttp (from $GOROOT)
> 	/go/src/golang.org/x/net/context/ctxhttp (from $GOPATH)
> golang.org/x/tools/internal/lsp/source/analysis.go:20:2: cannot find package "golang.org/x/sync/errgroup" in any of:
> 	/usr/local/go/src/golang.org/x/sync/errgroup (from $GOROOT)
> 	/go/src/golang.org/x/sync/errgroup (from $GOPATH)
> golang.org/x/tools/cmd/html2article/conv.go:21:2: cannot find package "golang.org/x/net/html" in any of:
> 	/usr/local/go/src/golang.org/x/net/html (from $GOROOT)
> 	/go/src/golang.org/x/net/html (from $GOPATH)
> golang.org/x/tools/cmd/html2article/conv.go:22:2: cannot find package "golang.org/x/net/html/atom" in any of:
> 	/usr/local/go/src/golang.org/x/net/html/atom (from $GOROOT)
> 	/go/src/golang.org/x/net/html/atom (from $GOPATH)
> golang.org/x/tools/playground/socket/socket.go:37:2: cannot find package "golang.org/x/net/websocket" in any of:
> 	/usr/local/go/src/golang.org/x/net/websocket (from $GOROOT)
> 	/go/src/golang.org/x/net/websocket (from $GOPATH)
> Service 'analyzer' failed to build: The command '/bin/sh -c go get -u ./...' returned a non-zero code: 1

**Comment by markus-wa** [comment] 2019-07-19 10:09
`go get github.com/markus-wa/demoinfocs-golang@issue-119-ItemPickup-UniqueID` should do the trick.

You can use any git identifier such as branch names, tags, commit SHAs, `HEAD` etc. after the `@` iirc.

**Comment by markus-wa** [comment] 2019-07-19 10:11
Oh and you'll need to use `ItemPickup.WeaponTraceable()` for it to work. Unfortunately I didn't see a straight forward way to fix `ItemPickup.Weapon`.

**Comment by xavier-rodet** [comment] 2019-07-19 12:48
Thanks !


I'll try it ASAP (probably Monday)

**Comment by xavier-rodet** [comment] 2019-07-22 09:17
I might have tried this already but got this error :

> go: cannot use path@version syntax in GOPATH mode

But with `GO111MODULE=on` environment variable added it works 👍 

However i don't understand how to access WeaponTraceable() ?

I tried : 
```go
    p.RegisterEventHandler(func(e events.ItemDrop) {

        if(isGameLive) {

            fmt.Printf("Player %s Dropped weapon %s (%d)\n", e.Player.Name, e.Weapon.Weapon.String(), e.WeaponTraceable().UniqueID())
        }
    })

    p.RegisterEventHandler(func(e events.ItemPickup) {

        if(isGameLive) {

            fmt.Printf("Player %s Picked up weapon %s (%d)\n", e.Player.Name, e.Weapon.Weapon.String(), e.WeaponTraceable().UniqueID())
        }
    })
```

Error : 

> app/app.go:54:104: e.WeaponTraceable undefined (type events.ItemDrop has no field or method WeaponTraceable)
> app/app.go:62:106: e.WeaponTraceable undefined (type events.ItemPickup has no field or method WeaponTraceable)
>

**Comment by markus-wa** [comment] 2019-07-22 16:16
Hmm, strange. For `ItemPickup.WeaponTraceable().UniqueID()` should work, actually.
`ItemDrop` & `ItemEquip` don't need `WeaponTraceable()`, for these `Weapon` or `WeaponPtr` should work fine.

Can you:
1. `export GO111MODULE=on`
2. `go get github.com/markus-wa/demoinfocs-golang@issue-119-ItemPickup-UniqueID` (again, just to really make sure it didn't reset something, somehow)
3. post your `go.mod` & `go.sum` files?

**Comment by xavier-rodet** [comment] 2019-07-22 19:38
I don't have any `go.mod` & `go.sum` files in my project folder.

Here's my docker configuration :

```
FROM golang:1.12-alpine

# Update package list
RUN apk update

# Install git
RUN apk add git

WORKDIR /app/

# GO111MODULE must be turned off to works
ENV GO111MODULE=off
RUN go mod init demo-analyzer

# GO111MODULE must be turned on to works
ENV GO111MODULE=on
RUN go get github.com/markus-wa/demoinfocs-golang@issue-119-ItemPickup-UniqueID

CMD ["go", "run", "/app/app.go"]
```

I added `go mod init` as it is needed to create `go.mod` & `go.sum` (if i'm right?) but I still don't see thoses files ... (and i'm still getting the same error)

Sorry i'm totally lost with go :p 

PS: i was indeed working inside `GOPATH` but not anymore now

**Comment by markus-wa** [comment] 2019-07-22 21:45
`ENV GO111MODULE=off` - I'm pretty sure this is wrong.

I'd remove both `ENV GO111MODULE=off` and `ENV GO111MODULE=on`.
Then it should work. It will automatically detect that you are outside the `GOPATH` and will create the files.
With `GO111MODULE=off`, `go mod init` doesn't work for me either, without `GO111MODULE` or `GO111MODULE=on` it works.

**Comment by xavier-rodet** [comment] 2019-07-23 14:04
Sorry, i tried everything i could without any result ...

Here's my Dockerfile (with old tests disabled) :
```
FROM golang:1.12-alpine

# Update package list
RUN apk update

# Install git
RUN apk add git

# Install vgo to use specific version of packages (See: https://godoc.org/golang.org/x/vgo)
#RUN go get -u golang.org/x/vgo

#COPY src /go/src
WORKDIR /app/

# init module for the project
RUN go mod init demo-analyzer

# TMP TEST BRANCH
#RUN vgo get github.com/markus-wa/demoinfocs-golang@issue-119-ItemPickup-UniqueID
#RUN go get gopkg.in/markus-wa/demoinfocs-golang.issue-119-ItemPickup-UniqueID
RUN go get github.com/markus-wa/demoinfocs-golang@issue-119-ItemPickup-UniqueID

CMD ["go", "run", "/app/app.go"]
``` 

Docker output (it does build) : 

> Building analyzer
> Step 1/8 : FROM golang:1.12-alpine
>  ---> 4e4b7a8b9495
> Step 2/8 : RUN apk update
>  ---> Using cache
>  ---> 63615f87ceef
> Step 3/8 : RUN apk add git
>  ---> Using cache
>  ---> d0436b3670c0
> Step 4/8 : WORKDIR /app/
>  ---> Running in c6159157a115
> Removing intermediate container c6159157a115
>  ---> 23a264e21fb0
> Step 5/8 : RUN go mod init demo-analyzer
>  ---> Running in 1aa51eb71bd0
> go: creating new go.mod: module demo-analyzer
> Removing intermediate container 1aa51eb71bd0
>  ---> a3b550f53091
> Step 6/8 : RUN go get github.com/markus-wa/demoinfocs-golang@issue-119-ItemPickup-UniqueID
>  ---> Running in 10216bc113b2
> go: finding github.com/markus-wa/demoinfocs-golang issue-119-ItemPickup-UniqueID
> go: finding github.com/dustin/go-heatmap v0.0.0-20180603032536-b89dbd73785a
> go: finding github.com/golang/freetype v0.0.0-20170609003504-e2365dfdc4a0
> go: finding github.com/llgcode/draw2d v0.0.0-20180124133339-274031cf2abe
> go: finding github.com/markus-wa/quickhull-go v0.0.0-20190116183559-9fb9702adbda
> go: finding github.com/gogo/protobuf v1.1.1
> go: finding github.com/llgcode/ps v0.0.0-20150911083025-f1443b32eedb
> go: finding github.com/stretchr/objx v0.1.1
> go: finding github.com/markus-wa/godispatch v1.1.0
> go: finding github.com/stretchr/testify v1.2.2
> go: finding golang.org/x/image v0.0.0-20180708004352-c73c2afc3b81
> go: finding github.com/markus-wa/gobitread v0.2.2
> go: finding github.com/pmezard/go-difflib v1.0.0
> go: finding github.com/davecgh/go-spew v1.1.1
> go: finding github.com/golang/geo v0.0.0-20180826223333-635502111454
> go: downloading github.com/markus-wa/demoinfocs-golang v1.2.2-0.20190718222654-0b073fe5c643
> go: extracting github.com/markus-wa/demoinfocs-golang v1.2.2-0.20190718222654-0b073fe5c643
> go: downloading github.com/golang/geo v0.0.0-20180826223333-635502111454
> go: downloading github.com/gogo/protobuf v1.1.1
> go: downloading github.com/markus-wa/godispatch v1.1.0
> go: downloading github.com/markus-wa/quickhull-go v0.0.0-20190116183559-9fb9702adbda
> go: extracting github.com/markus-wa/godispatch v1.1.0
> go: extracting github.com/markus-wa/quickhull-go v0.0.0-20190116183559-9fb9702adbda
> go: downloading github.com/markus-wa/gobitread v0.2.2
> go: extracting github.com/markus-wa/gobitread v0.2.2
> go: extracting github.com/golang/geo v0.0.0-20180826223333-635502111454
> go: extracting github.com/gogo/protobuf v1.1.1
> Removing intermediate container 10216bc113b2
>  ---> be66c6a6b5bd
> Step 7/8 : EXPOSE 80
>  ---> Running in 633aff9670b7
> Removing intermediate container 633aff9670b7
>  ---> 16e22f3a1e5f
> Step 8/8 : CMD ["go", "run", "/app/app.go"]
>  ---> Running in 71966e43d552
> Removing intermediate container 71966e43d552
>  ---> e2240c086fcd
> 
> Successfully built e2240c086fcd


Error on execution : 

> app.go:8:2: cannot find package "github.com/markus-wa/demoinfocs-golang" in any of:
> 	/usr/local/go/src/github.com/markus-wa/demoinfocs-golang (from $GOROOT)
> 	/go/src/github.com/markus-wa/demoinfocs-golang (from $GOPATH)
> app.go:9:2: cannot find package "github.com/markus-wa/demoinfocs-golang/events" in any of:
> 	/usr/local/go/src/github.com/markus-wa/demoinfocs-golang/events (from $GOROOT)
> 	/go/src/github.com/markus-wa/demoinfocs-golang/events (from $GOPATH)

Your package is not stored in `/go/src/` or `/usr/local/go/src/` and there is no `go.mod` & `go.sum` inside my module.

**Comment by markus-wa** [comment] 2019-07-23 14:38
```
Step 5/8 : RUN go mod init demo-analyzer
---> Running in 1aa51eb71bd0
go: creating new go.mod: module demo-analyzer
```
seems to work, can you put a `RUN cat go.mod` after `RUN go mod init demo-analyzer`, I'm sure the file is there.

The issue might be with `go run /app/app.go`

I'll try it out at home, I currently don't have a machine with docker around.

**Comment by markus-wa** [comment] 2019-07-23 21:06
I tried it on my machine and everything works as expected.

Here are two working examples: https://drive.google.com/file/d/1o_kaxf0qUIKZRjmTirwe4ZOnz3nxAVor/view?usp=sharing

In each of the two folders you can just build & run the containers via:
1. `docker build .`
2. `docker run <container-ID>`

Also ideally you should have `go.mod` & `go sum` checked into your repo, not just in the docker container (see 'better' example).

**Comment by xavier-rodet** [comment] 2019-07-24 08:33
Thanks for the samples, it's working ... the only difference from me is that i was using docker-compose to bind my project local files into the docker container instead of copying it inside ... weird ....

So after testing again with `ItemPickup.WeaponTraceable().UniqueID()` it does work as expected !

> Round 4 has just started
> ...
> Player KRIMZ Dropped weapon AK-47 (8373100031395864307)
> Player Brollan Picked up weapon AK-47 (8373100031395864307)

👍

**Comment by markus-wa** [comment] 2019-07-24 13:36
Awesome, thanks!

**Closed** 2019-07-24 13:36 UTC
Labels: bug, fixed / implemented

**Comment by markus-wa** [comment] 2020-04-12 15:59
It seems like the root cause for `ItemPickup.Weapon` not being the same as `ItemPickup.WeaponTraceable()` has now been fixed.

I'm not sure when or how but the two values now seem to be consistent.

I will remove `WeaponTraceble` from v2.0.0
