### ISSUE TITLE
header.FrameRate() fallback

### ISSUE THREAD

**Issue by 87andrewh** [markus-wa/demoinfocs-golang#235] opened 2020-08-26 07:14 UTC
**Higher goal**
Allow header.FrameRate() to return the correct demo framerate even when the demo header is corrupted. 

**Describe the solution you'd like**
One workaround is advancing the demo one frame and using the change in Parser.GameState().IngameTick() to calculate the framerate.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by markus-wa** [comment] 2020-08-26 08:10
Hi @87andrewh 👋

Thanks for the report!

What's the higher goal here, I assume you want to use that FrameRate for something? Have you considered using `Parser.TickRate` instead? (I know the two values aren't the same, but depending on what you're doing it could still work).

Overall I agree this should be fixed thoug, probably as a new function called `Parser.FrameRate()` rather than in `Header.FrameRate()` (as we'd have to add some strange callbacks otherwise).

**Comment by 87andrewh** [comment] 2020-08-26 08:17
I need FrameRate because I'm building a program that analyzes high-frequency aim data, so I need to standardize and filter out "bad" demos that have low frame and tick rates.

**Comment by markus-wa** [comment] 2020-08-26 08:45
That makes sense, thanks for clarifying.

If you'd like you can attempt a PR for this (see how `Parser.TickRate()` works).
Otherwise I'll try to get to it over the coming weekend.

**Comment by 87andrewh** [comment] 2020-08-26 19:24
I'm a bit busy right now, and my fix is slightly troublesome because it requires advancing one frame. I'll see if I have time to implement a cleaner fix.

**Comment by markus-wa** [comment] 2020-08-26 21:45
If you can find another way that'd be great but I'd be happy to accept the fix where we have to advance a frame with a fallback to the demo header value. Honestly though I don't there is another way than advancing a tick.

**Comment by 87andrewh** [comment] 2020-08-26 21:47
Hmm, I was thinking of a way to reopen the demo in a new temporary parser to advance the tick without affecting the correctness of the main parser.

**Comment by 87andrewh** [comment] 2020-08-26 22:01
Oh, I should note that you actually have to advance ~50 frames to get out of their weird corrupted header zone.

**Comment by markus-wa** [comment] 2020-08-26 22:08
> I was thinking of a way to reopen the demo in a new temporary parser

hm, not a fan of that approach tbh.

> Oh, I should note that you actually have to advance ~50 frames to get out of their weird corrupted (or even uncorrupted) header zone.

I don't think that's too much of an issue. 50 frames is not a lot and we can possibly add a new event to signal this, something like `FrameRateCalculated` to streamline this. I doubt there's a usecase where this approach would be an issue and the code will be much cleaner.

**Comment by 87andrewh** [comment] 2020-08-26 22:14
The rough fix that I use now now:	
```
p := dem.NewParser(f)

//  tick can be erroneous when 0, so wait for it to hit a value between 2 and 30
tick := -1
for !(2 < tick && tick < 30) {
	_, err = p.ParseNextFrame()
	checkError(err)
	tick = p.GameState().IngameTick()
}
_, err = p.ParseNextFrame()
checkError(err)
nextTick := p.GameState().IngameTick()

fmt.Printf("Demo FrameRate: %d\n", int(p.TickRate())/(nextTick-tick))
```

**Comment by markus-wa** [comment] 2020-09-06 16:08
could you send a few of these corrupt demos my way? I might have a fix in #237 but I'm not sure, it's a bit messy

**Comment by 87andrewh** [comment] 2020-09-07 07:49
Hmm, I forgot which demos were corrupt. I deleted a few, and I can't seem to find more. Thus I cannot reproduce my original error. I rewrote some code and called p.ParseHeader().FrameRate(), and now it seems to work fine on 10 random demos I selected.

I really hope I didn't throw you on a wild goose chase due to an old typo. I'll let you know if I run into more corrupt demos.

**Comment by markus-wa** [comment] 2020-09-07 08:08
> I reeeeally hope I didn't throw you on a wild goose chase due to an old typo.

No worries, I have one demo that reproduces this. I just need a few more to verify the fix works with all demos!

**Comment by LarsKoelpin** [comment] 2020-09-09 08:43
i think a few hltv demo's have this bug. 

e.g. (I think dust2) https://www.hltv.org/download/demo/57174

**Comment by markus-wa** [comment] 2020-09-09 18:02
@LarsKoelpin afaik it happens when the map is changed without calling the `stop` command. But just producing testdata locally isn't really valuable as there might be other factors at play.

thanks for that demo btw, unfortunately this one shows that the fix doesn't really work :(
back to the drawing board

**Comment by LarsKoelpin** [comment] 2020-09-09 19:43
glad I could help.

I can confirm, that the proposed fix works for me tho

**Comment by markus-wa** [comment] 2020-09-10 11:35
> I can confirm, that the proposed fix from above works for me tho

Sort of, it returns a number that is pretty close to the actual frame-rate, but that number is not (always) correct

**Comment by markus-wa** [comment] 2024-10-14 11:57
Closing as CS2 works a bit differently anyway

**Closed by markus-wa** 2024-10-14 11:57 UTC
Labels: kind: enhancement, needs: investigation (maintainer), corrupt demos
