### ISSUE TITLE
another "unconnected" player issue

### ISSUE THREAD

**Issue by BestAwperEver** [markus-wa/demoinfocs-golang#172] opened 2019-12-09 22:25 UTC
This issue is something between "bug report" and "feature request" and may even be considered a note to the way the library is processing `unconnected` players right now.

There are some cases when `Killer` and `Victim` in `Kill` event and `Attacker` and `Player` in `PlayerHurt` event are `nil`'s when in game we actually have them as `unconnected`. It happens when a player was neither connected nor got binded by the library as `unconnected` so their `userid` cannot be found in `playersByUserID`.

Sample parser output from parsing the first (knife) round of
https://www.hltv.org/download/demo/54130 (map 1 -- Inferno)
(only events containing `nil` players):
```
DEBUG: tick 132: VandaL cs.money hurt (nil) with Knife (67 hp left, 33 damage)
DEBUG: tick 136: (nil) hurt VandaL cs.money with Knife (45 hp left, 55 damage)
DEBUG: tick 196: VandaL cs.money hurt (nil) with Knife (46 hp left, 21 damage)
DEBUG: tick 204: s4 cs.money hurt (nil) with Knife (0 hp left, 55 damage)
DEBUG: tick 204: s4 cs.money killed <Knife> (nil)
DEBUG: tick 272: (nil) hurt R0MN3D cs.money with Knife (45 hp left, 55 damage)
DEBUG: tick 304: (nil) hurt chups cs.money with Knife (0 hp left, 55 damage)
DEBUG: tick 304: (nil) killed <Knife> chups cs.money
DEBUG: tick 436: R0MN3D cs.money hurt (nil) with Knife (45 hp left, 55 damage)
DEBUG: tick 444: (nil) hurt R0MN3D cs.money with Knife (0 hp left, 55 damage)
DEBUG: tick 444: (nil) killed <Knife> R0MN3D cs.money
DEBUG: tick 496: muR hurt (nil) with Knife (0 hp left, 55 damage)
DEBUG: tick 496: muR killed <Knife> (nil)
DEBUG: tick 572: (nil) hurt muR with Knife (0 hp left, 55 damage)
DEBUG: tick 572: (nil) killed <Knife> muR
DEBUG: tick 828: (nil) hurt s4 cs.money with Knife (0 hp left, 33 damage)
DEBUG: tick 828: (nil) killed <Knife> s4 cs.money
DEBUG: tick 828: nil mvp player
```

This is not exaclty a bug, because GOTV also has problems with "unconnected" players, but let's have a look at the screenshot:
![20191209235052_1](https://user-images.githubusercontent.com/24738447/70472518-41f82780-1ae0-11ea-8824-cf2193eff129.jpg)
(the player actually has knife model, it's just not in the screenshot because it is being swung atm)

Here we can see several points of interest:
1) GOTV recognizes kills by "unconnected" players as some sort of suicide, but the killed player seems to be in spectators or unussigned team at the left side; that's more or less goes in line with `nil` killer in our event
2) However, GOTV keeps track of the player (we can see 123 ADR) , while we don't -- we just have a `nil` pointer
3) Also GOTV has information about the weapon's owner (`scoobyxie`), while in parser we don't have that: `Owner` of the knife is also `nil`. I suppose that for further conversation we can safely assume that the player's name `scoobyxie` since you cannot drop knives in competitive CSGO.

What I cannot explain is the following: we actually _have_ raw player corresponding to `scoobyxie` in the exact same tick he kills `s4 cs.money` with valid `guid` and `userid`: it's `STEAM_1:0:21699287` and `54`.

I don't really think that this is something that should be "fixed" right now, but surely there is a way to match at least some `nil` players to existing ones so we can have extra information and ability to work with such players. May be even more than GOTV has (in a way it shows it)!

Right now I'm quite sleepy and maybe made some mistakes in my reasoning but I feel like I should have write this anyway so it doesn't pass unnoticed 😃

**Comment by markus-wa** [comment] 2019-12-12 22:12
I think this is a duplicate of #156.

The issue doesn't seem to be that we don't know about the player (I think) but rather that we can't link the events to the player. This is also what's observable in GOTV in the kill feed.

Maybe it's worth another investigation but so far I haven't actually seen this happen in any 'valid' round (here it also seems to be during warmup), so I'm not sure I'd want to spend too much time on it right now 😅.

**Comment by markus-wa** [comment] 2019-12-12 22:16
Either way, you mentioned a few fields where this occurs that don't have the necessary documentation yet, so that will certainly be an open point.

**Comment by BestAwperEver** [comment] 2019-12-13 11:32
Yes is does indeed look like a duplicate of #156. Didn't look it in because of the name -- thought it is connected to world damage.

One more thing I noticed: `scoobyxie`'s `userid` in `rawPlayers` is 54, in the `Kill` event raw data it is 51, but in `playersByUserID` we have neither of these.

**Comment by markus-wa** [comment] 2019-12-13 11:59
Could you check if the player is in `playersByEntityID` if you have the time?

I don't have go on the machine I'm on right now.

**Comment by BestAwperEver** [comment] 2019-12-13 12:19
We surely have him there as "unknown" player:
![image](https://user-images.githubusercontent.com/24738447/70799756-95f25d00-1dbb-11ea-8f3b-e9f30c022c14.png)
Not only because we have everyone else as valid players in this map but also because it is the only player which belongs to CT team, has 100 hp, 100 ap and a "stiletto" knife (`models/weapons/v_knife_stiletto.mdl`).

**Comment by markus-wa** [comment] 2019-12-24 13:06
I will check if we have some other way of correlating entity-ID and user-ID.

Maybe we can add some cache (map) on the `Parser` struct that will help us look up the entry in `playersByEntityID` if a player is missing from `playersByUserID`.

**Comment by markus-wa** [comment] 2019-12-26 11:35
So I couldn't find a way to correlate the two in this situation. userID 38, which is sent in the events in this example, is just nowhere to be found.

I guess the best we can do is document this.

I didn't add it everywhere yet as I couldn't confirm that it occurrs in some of the events. If it does we can always add the doc but I didn't want to over-document. I'd rather investigate this again later if it's causing more issues than expected.

**Comment by markus-wa** [comment] 2019-12-26 11:38
I will close this for now, feel free to re-open it if you have further questions or any other inputs.

**Closed by markus-wa** 2019-12-26 11:38 UTC
Labels: corrupt demos, wontfix
