### ISSUE TITLE
nil raw player inside bindNewPlayer()

### ISSUE THREAD

**Issue by BestAwperEver** [markus-wa/demoinfocs-golang#165] opened 2019-11-28 11:01 UTC
**Describe the bug**
At the very beginning of the demo (in-game tick is 0) there is a player entity with `entityID == 15` which is not present in `p.rawPlayers` at the moment of binding.

**To Reproduce**
First map (de_inferno) of
https://www.hltv.org/download/demo/54203

Code:
Conditional breakpoint on `datatables.go`, line 196 with condition `rp == nil`.

**Expected behavior**
`p.rawPlayers` containing an entry for the player entity with `entityID == 15`.

**Library version**
v1.4.0, v1.5.1

**Additional info**
I dug a bit into this demo and it seems that this player is a _sixth_ terrorist which is present at the warmup. He has no name, no userpic, no scoreboard entry and also is not shown on the radar. Not much here to work with 😃 
The decision to treat him as GOTV does seems to be more than acceptable but the only one we have. Probable should give him some fake but unique (steam?)id (in case there will be several such players) and a flag that he is not processed correctly.

**Comment by BestAwperEver** [comment] 2019-11-28 11:03
Just realized it's probably the same as #162. Will wait for the fix

**Comment by markus-wa** [comment] 2019-11-28 16:42
yupp, that's a dupe of #162, hoping to fix it over the weekend.

**Comment by markus-wa** [comment] 2019-11-28 20:28
This should be fixed with [`v1.6.0-rc0`](https://github.com/markus-wa/demoinfocs-golang/releases/tag/v1.6.0-rc0) or PR #163. Please verify.

If it works I will merge to master and do a proper release.

**Comment by markus-wa** [comment] 2019-11-28 21:48
Fixed

**Closed by markus-wa** 2019-11-28 21:48 UTC
Labels: duplicate, fixed / implemented
