### ISSUE TITLE
How to handle compressed files?

### ISSUE THREAD

**Issue by sirherrbatka** [markus-wa/demoinfocs-golang#300] opened 2021-06-15 09:59 UTC
Hi, 

I am having trouble working with gziped demo files using this library. I was expecting that simply creating a new gzip reader and passing the reader to the NewParser will be fine, but i am getting error related to unmarshal. Same result if am trying to decompress using zcat and FIFO file pipe into go process. I think that I am doing this wrong, but I can't seem to find what exactly.

**Comment by markus-wa** [comment] 2021-06-15 10:05
Hi @sirherrbatka 

See #299 - for now you can work around this by doing `https://golang.org/pkg/io/#ReadAll`

but I'm hoping to fix this soon :slightly_smiling_face:

**Comment by markus-wa** [comment] 2021-06-15 10:06
the issue is the same for gzip and HTTP bodies - with the problem being that the reader may not have all bytes available at all times right now. this is a bug in gobitread, one of my other packages

I'll close this now and we can leave any discussion on 299

**Closed by markus-wa** 2021-06-15 10:06 UTC

**Comment by sirherrbatka** [comment] 2021-06-15 10:08
Thanks for a quick answer! Unfortunately, I can't afford to read all, so I guess I will simply decompress the file beforehand. I will keep eye on that HTTP issue, once this can be solved I will have less IO to deal with.

**Comment by markus-wa** [comment] 2021-06-15 10:16
makes sense. please note that this library is very heavy on memory usage in general, so parsing a demo will likely result in memory usage higher than the demo file is in size, even without `ReadAll()`.

this is because of the way parsing and processing is split into two asynchronous parts and because we need to create a ton of temporary pointer objects for the game's network-messages, which then only get GCd occasionally.

you can probably reduce memory usage further by setting `ParserConfig.MsgQueueBufferSize` to 0, 1 or some other low number, which limits the amount of asynchronicity the parser does.
